// Auto-generated by zitejs generate. Do not edit manually.

import { createCaller } from 'zitejs/caller';

import type { default as _AdminExerciseEp } from '../src/api/adminExercise';
import type { default as _FinishWorkoutEp } from '../src/api/finishWorkout';
import type { default as _GetAchievementsEp } from '../src/api/getAchievements';
import type { default as _GetAdminEp } from '../src/api/getAdmin';
import type { default as _GetBmiHistoryEp } from '../src/api/getBmiHistory';
import type { default as _GetDashboardEp } from '../src/api/getDashboard';
import type { default as _GetExercisesEp } from '../src/api/getExercises';
import type { default as _GetHistoryEp } from '../src/api/getHistory';
import type { default as _GetMeasurementsEp } from '../src/api/getMeasurements';
import type { default as _GetProfileEp } from '../src/api/getProfile';
import type { default as _GetProgressEp } from '../src/api/getProgress';
import type { default as _LogExerciseEp } from '../src/api/logExercise';
import type { default as _ManageGoalsEp } from '../src/api/manageGoals';
import type { default as _ManagePlansEp } from '../src/api/managePlans';
import type { default as _ManageRemindersEp } from '../src/api/manageReminders';
import type { default as _SaveBmiEp } from '../src/api/saveBmi';
import type { default as _SaveMeasurementEp } from '../src/api/saveMeasurement';
import type { default as _SaveProfileEp } from '../src/api/saveProfile';
import type { default as _StartWorkoutEp } from '../src/api/startWorkout';
import type { default as _ToggleFavoriteEp } from '../src/api/toggleFavorite';

type _AdminExerciseCfg = typeof _AdminExerciseEp;
export type AdminExerciseInputType = NonNullable<_AdminExerciseCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_AdminExerciseCfg['execute']>[0]['input'];
export type AdminExerciseOutputType = Awaited<ReturnType<_AdminExerciseCfg['execute']>>;
export const adminExercise = createCaller<AdminExerciseInputType, AdminExerciseOutputType>('adminExercise');

type _FinishWorkoutCfg = typeof _FinishWorkoutEp;
export type FinishWorkoutInputType = NonNullable<_FinishWorkoutCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_FinishWorkoutCfg['execute']>[0]['input'];
export type FinishWorkoutOutputType = Awaited<ReturnType<_FinishWorkoutCfg['execute']>>;
export const finishWorkout = createCaller<FinishWorkoutInputType, FinishWorkoutOutputType>('finishWorkout');

type _GetAchievementsCfg = typeof _GetAchievementsEp;
export type GetAchievementsInputType = NonNullable<_GetAchievementsCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_GetAchievementsCfg['execute']>[0]['input'];
export type GetAchievementsOutputType = Awaited<ReturnType<_GetAchievementsCfg['execute']>>;
export const getAchievements = createCaller<GetAchievementsInputType, GetAchievementsOutputType>('getAchievements');

type _GetAdminCfg = typeof _GetAdminEp;
export type GetAdminInputType = NonNullable<_GetAdminCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_GetAdminCfg['execute']>[0]['input'];
export type GetAdminOutputType = Awaited<ReturnType<_GetAdminCfg['execute']>>;
export const getAdmin = createCaller<GetAdminInputType, GetAdminOutputType>('getAdmin');

type _GetBmiHistoryCfg = typeof _GetBmiHistoryEp;
export type GetBmiHistoryInputType = NonNullable<_GetBmiHistoryCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_GetBmiHistoryCfg['execute']>[0]['input'];
export type GetBmiHistoryOutputType = Awaited<ReturnType<_GetBmiHistoryCfg['execute']>>;
export const getBmiHistory = createCaller<GetBmiHistoryInputType, GetBmiHistoryOutputType>('getBmiHistory');

type _GetDashboardCfg = typeof _GetDashboardEp;
export type GetDashboardInputType = NonNullable<_GetDashboardCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_GetDashboardCfg['execute']>[0]['input'];
export type GetDashboardOutputType = Awaited<ReturnType<_GetDashboardCfg['execute']>>;
export const getDashboard = createCaller<GetDashboardInputType, GetDashboardOutputType>('getDashboard');

type _GetExercisesCfg = typeof _GetExercisesEp;
export type GetExercisesInputType = NonNullable<_GetExercisesCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_GetExercisesCfg['execute']>[0]['input'];
export type GetExercisesOutputType = Awaited<ReturnType<_GetExercisesCfg['execute']>>;
export const getExercises = createCaller<GetExercisesInputType, GetExercisesOutputType>('getExercises');

type _GetHistoryCfg = typeof _GetHistoryEp;
export type GetHistoryInputType = NonNullable<_GetHistoryCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_GetHistoryCfg['execute']>[0]['input'];
export type GetHistoryOutputType = Awaited<ReturnType<_GetHistoryCfg['execute']>>;
export const getHistory = createCaller<GetHistoryInputType, GetHistoryOutputType>('getHistory');

type _GetMeasurementsCfg = typeof _GetMeasurementsEp;
export type GetMeasurementsInputType = NonNullable<_GetMeasurementsCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_GetMeasurementsCfg['execute']>[0]['input'];
export type GetMeasurementsOutputType = Awaited<ReturnType<_GetMeasurementsCfg['execute']>>;
export const getMeasurements = createCaller<GetMeasurementsInputType, GetMeasurementsOutputType>('getMeasurements');

type _GetProfileCfg = typeof _GetProfileEp;
export type GetProfileInputType = NonNullable<_GetProfileCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_GetProfileCfg['execute']>[0]['input'];
export type GetProfileOutputType = Awaited<ReturnType<_GetProfileCfg['execute']>>;
export const getProfile = createCaller<GetProfileInputType, GetProfileOutputType>('getProfile');

type _GetProgressCfg = typeof _GetProgressEp;
export type GetProgressInputType = NonNullable<_GetProgressCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_GetProgressCfg['execute']>[0]['input'];
export type GetProgressOutputType = Awaited<ReturnType<_GetProgressCfg['execute']>>;
export const getProgress = createCaller<GetProgressInputType, GetProgressOutputType>('getProgress');

type _LogExerciseCfg = typeof _LogExerciseEp;
export type LogExerciseInputType = NonNullable<_LogExerciseCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_LogExerciseCfg['execute']>[0]['input'];
export type LogExerciseOutputType = Awaited<ReturnType<_LogExerciseCfg['execute']>>;
export const logExercise = createCaller<LogExerciseInputType, LogExerciseOutputType>('logExercise');

type _ManageGoalsCfg = typeof _ManageGoalsEp;
export type ManageGoalsInputType = NonNullable<_ManageGoalsCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_ManageGoalsCfg['execute']>[0]['input'];
export type ManageGoalsOutputType = Awaited<ReturnType<_ManageGoalsCfg['execute']>>;
export const manageGoals = createCaller<ManageGoalsInputType, ManageGoalsOutputType>('manageGoals');

type _ManagePlansCfg = typeof _ManagePlansEp;
export type ManagePlansInputType = NonNullable<_ManagePlansCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_ManagePlansCfg['execute']>[0]['input'];
export type ManagePlansOutputType = Awaited<ReturnType<_ManagePlansCfg['execute']>>;
export const managePlans = createCaller<ManagePlansInputType, ManagePlansOutputType>('managePlans');

type _ManageRemindersCfg = typeof _ManageRemindersEp;
export type ManageRemindersInputType = NonNullable<_ManageRemindersCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_ManageRemindersCfg['execute']>[0]['input'];
export type ManageRemindersOutputType = Awaited<ReturnType<_ManageRemindersCfg['execute']>>;
export const manageReminders = createCaller<ManageRemindersInputType, ManageRemindersOutputType>('manageReminders');

type _SaveBmiCfg = typeof _SaveBmiEp;
export type SaveBmiInputType = NonNullable<_SaveBmiCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_SaveBmiCfg['execute']>[0]['input'];
export type SaveBmiOutputType = Awaited<ReturnType<_SaveBmiCfg['execute']>>;
export const saveBmi = createCaller<SaveBmiInputType, SaveBmiOutputType>('saveBmi');

type _SaveMeasurementCfg = typeof _SaveMeasurementEp;
export type SaveMeasurementInputType = NonNullable<_SaveMeasurementCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_SaveMeasurementCfg['execute']>[0]['input'];
export type SaveMeasurementOutputType = Awaited<ReturnType<_SaveMeasurementCfg['execute']>>;
export const saveMeasurement = createCaller<SaveMeasurementInputType, SaveMeasurementOutputType>('saveMeasurement');

type _SaveProfileCfg = typeof _SaveProfileEp;
export type SaveProfileInputType = NonNullable<_SaveProfileCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_SaveProfileCfg['execute']>[0]['input'];
export type SaveProfileOutputType = Awaited<ReturnType<_SaveProfileCfg['execute']>>;
export const saveProfile = createCaller<SaveProfileInputType, SaveProfileOutputType>('saveProfile');

type _StartWorkoutCfg = typeof _StartWorkoutEp;
export type StartWorkoutInputType = NonNullable<_StartWorkoutCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_StartWorkoutCfg['execute']>[0]['input'];
export type StartWorkoutOutputType = Awaited<ReturnType<_StartWorkoutCfg['execute']>>;
export const startWorkout = createCaller<StartWorkoutInputType, StartWorkoutOutputType>('startWorkout');

type _ToggleFavoriteCfg = typeof _ToggleFavoriteEp;
export type ToggleFavoriteInputType = NonNullable<_ToggleFavoriteCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_ToggleFavoriteCfg['execute']>[0]['input'];
export type ToggleFavoriteOutputType = Awaited<ReturnType<_ToggleFavoriteCfg['execute']>>;
export const toggleFavorite = createCaller<ToggleFavoriteInputType, ToggleFavoriteOutputType>('toggleFavorite');


export const api = {
  adminExercise,
  finishWorkout,
  getAchievements,
  getAdmin,
  getBmiHistory,
  getDashboard,
  getExercises,
  getHistory,
  getMeasurements,
  getProfile,
  getProgress,
  logExercise,
  manageGoals,
  managePlans,
  manageReminders,
  saveBmi,
  saveMeasurement,
  saveProfile,
  startWorkout,
  toggleFavorite,
};
