import test from 'node:test';
import assert from 'node:assert/strict';
import {spawn} from 'node:child_process';
import {mkdtempSync,rmSync} from 'node:fs';
import {tmpdir} from 'node:os';
import path from 'node:path';
const temp=mkdtempSync(path.join(tmpdir(),'fittracker-test-'));
const base='http://127.0.0.1:3019';
let child;
async function start(){child=spawn(process.execPath,['server-dist/server/index.js'],{env:{...process.env,NODE_ENV:'test',DATABASE_URL:'',PORT:'3019',LOCAL_DB_PATH:path.join(temp,'test.sqlite'),ADMIN_EMAILS:'admin@example.test'},stdio:['ignore','pipe','pipe']});let output='';child.stderr.on('data',b=>output+=b);for(let i=0;i<100;i++){if(child.exitCode!==null)throw new Error(output);try{if((await fetch(base+'/api/health')).ok)return;}catch{}await new Promise(r=>setTimeout(r,100));}throw new Error('Server did not start: '+output);}
async function stop(){if(child && child.exitCode===null){const done=new Promise(r=>child.once('exit',r));child.kill();await done;}}
async function call(name,input={},cookie='',method='POST',headers={}){const r=await fetch(base+'/api/'+name,{method,headers:{...(method==='POST'?{'Content-Type':'application/json'}:{}),...(cookie?{Cookie:cookie}:{}),...headers},...(method==='POST'?{body:JSON.stringify(input)}:{})});return {status:r.status,data:await r.json(),cookie:r.headers.get('set-cookie')?.split(';')[0]};}
test('Original app APIs, ownership boundaries, and persistent storage',async()=>{try{
  await start();
  assert.equal((await call('getDashboard')).status,401);
  const admin=await call('auth/register',{name:'Admin',email:'admin@example.test',password:'testing-pass-123'});assert.equal(admin.status,201);
  const alice=await call('auth/register',{name:'Alice',email:'alice@example.test',password:'testing-pass-123'});assert.equal(alice.status,201);
  const bob=await call('auth/register',{name:'Bob',email:'bob@example.test',password:'testing-pass-123'});assert.equal(bob.status,201);
  const a=alice.cookie,b=bob.cookie,ad=admin.cookie;
  const starter=(await call('getExercises',{},a)).data.exercises;
  assert.equal(starter.length,12);
  for(const exercise of starter){assert.ok(exercise.instructions);assert.equal(exercise.steps.split('\n').length,4);assert.match(exercise.videoUrl,/^https:\/\/www.youtube.com\/watch\?v=[\w-]{11}$/);assert.match(exercise.sourceUrl,/^https:\/\/www.nasm.org\/resource-center\/exercise-library\//);}
  assert.equal((await call('getExercises',{search:'Push-Up'},a)).data.exercises.length,4);
  assert.equal((await call('auth/login',{email:'alice@example.test',password:'wrong'})).status,401);
  assert.equal((await call('getAdmin',{},a)).status,403);
  assert.equal((await call('getDashboard',{},a,'POST',{Origin:'https://unrelated.example'})).status,403);
  assert.equal((await call('saveProfile',{displayName:'Alice Fitness',height:170,weight:65},a)).status,200);
  assert.equal((await call('getProfile',{},a)).data.profile.displayName,'Alice Fitness');
  assert.equal((await call('saveBmi',{weight:65,height:170},a)).data.record.bmiValue,22.5);
  assert.equal((await call('saveBmi',{weight:65,height:0},a)).status,400);
  assert.equal((await call('getBmiHistory',{},b)).data.records.length,0);
  await call('saveMeasurement',{weight:65,waist:80},a);
  assert.equal((await call('getMeasurements',{},a)).data.records.length,1);
  const goal=(await call('manageGoals',{action:'create',name:'Test goal',targetValue:10},a)).data.goal;
  assert.equal((await call('manageGoals',{action:'update',id:goal.id,currentValue:99},b)).status,403);
  assert.equal((await call('manageGoals',{action:'delete',id:goal.id},b)).status,403);
  await call('manageGoals',{action:'update',id:goal.id,currentValue:5},a);
  assert.equal((await call('manageGoals',{action:'list'},a)).data.goals[0].currentValue,5);
  await call('managePlans',{action:'create',name:'Test plan'},a);
  const plan=(await call('managePlans',{action:'list'},a)).data.plans[0];
  await call('manageReminders',{action:'create',title:'Test reminder',days:['Monday'],time:'08:00'},a);
  const reminder=(await call('manageReminders',{action:'list'},a)).data.reminders[0];
  await call('manageReminders',{action:'update',id:reminder.id,active:false},a);
  assert.equal((await call('manageReminders',{action:'list'},a)).data.reminders[0].active,false);
  assert.equal((await call('adminExercise',{action:'create',name:'Test exercise'},a)).status,403);
  assert.equal((await call('adminExercise',{action:'create',name:'Test exercise',category:'Chest',defaultSets:3,defaultReps:10},ad)).status,200);
  const exercise=(await call('getExercises',{search:'Test exercise'},a)).data.exercises[0];
  await call('toggleFavorite',{exerciseId:exercise.id},a);
  const favorite=(await call('getExercises',{},a)).data.exercises.find(e=>e.id===exercise.id);assert.equal(favorite.isFavorite,true);
  assert.equal((await call('toggleFavorite',{exerciseId:exercise.id,favRecordId:favorite.favRecordId},b)).status,403);
  const session=(await call('startWorkout',{title:'Test workout',planId:plan.id},a)).data.session;
  assert.equal((await call('logExercise',{sessionId:session.id,exerciseId:exercise.id,setNumber:1,reps:10},b)).status,403);
  assert.equal((await call('logExercise',{sessionId:session.id,exerciseId:exercise.id,setNumber:1,reps:10},a)).status,200);
  const finish={sessionId:session.id,durationMinutes:10,totalExercises:1,totalSets:1,totalReps:10,caloriesBurned:5,completion:100};
  assert.equal((await call('finishWorkout',finish,b)).status,403);
  assert.equal((await call('finishWorkout',finish,a)).status,200);
  const history=(await call('getHistory',{},a)).data.sessions;assert.equal(history.length,1);assert.equal(history[0].title,'Test workout');assert.equal(history[0].user,alice.data.user.id);assert.equal(history[0].completion,1);
  assert.equal((await call('getAchievements',{},a)).data.achievements[0].achievementKey,'first_workout');
  assert.equal((await call('getDashboard',{},a)).data.data.totalWorkouts,1);
  assert.equal((await call('getProgress',{days:30},a)).data.data.sessions.length,1);
  assert.equal((await call('getAdmin',{},ad)).data.data.totalUsers,3);
  assert.equal((await call('getHistory',{},b)).data.sessions.length,0);
  const html=await fetch(base+'/dashboard');assert.match(await html.text(),/<div id="root"><\/div>/);
  await call('adminExercise',{action:'update',id:'starter-push-up',instructions:'Admin customized guide'},ad);
  await call('adminExercise',{action:'delete',id:'starter-side-plank'},ad);
  await stop();await start();
  const afterRestart=(await call('getExercises',{},a)).data.exercises;
  assert.equal(afterRestart.length,12);
  assert.equal(afterRestart.find(e=>e.id==='starter-push-up').instructions,'Admin customized guide');
  assert.equal(afterRestart.some(e=>e.id==='starter-side-plank'),false);
  assert.equal((await call('getHistory',{},a)).data.sessions[0].title,'Test workout');
  assert.equal((await call('auth/me',{},a,'GET')).data.user.email,'alice@example.test');
  await call('auth/logout',{},a);assert.equal((await call('getDashboard',{},a)).status,401);
  await call('manageReminders',{action:'delete',id:reminder.id},b);assert.equal((await call('manageReminders',{action:'list'},b)).data.reminders.length,0);
}finally{await stop();rmSync(temp,{recursive:true,force:true});}});
