// Auto-generated by zitejs generate. Do not edit manually.
//
// Usage in endpoint files (src/api/*.ts):
//   import { zite } from "zitejs/db";
//
// Always use "zitejs/db" — never use relative paths like "../../.zite/db".
// The tsconfig aliases resolve zitejs/* imports to the correct .zite/ files.
//
// Table client methods (all take a single params object):
//   .findAll({ filters?, sort?, offset?, limit?, fields? }) → { records: T[], hasMore: boolean }
//     filters: { fieldName: value } for equality, or { fieldName: { <op>: value } }
//     operators: contains, not, in, notIn, lt, lte, gt, gte
//       `not: null` means "is set". An empty `in: []` matches nothing; an
//       empty `notIn: []` applies no filter.
//     sort is currently IGNORED here — it is stripped before the request.
//       (it does work on zite.auth.findAllUsers). Order in SQL instead.
//     limit defaults to 500, max 2000; offset is a row count (a number)
//     a filter value of `undefined` is REJECTED (it would query unfiltered
//       and match an arbitrary record). Check the value first.
//   .findOne({ id?, filters?, fields? }) → T | undefined
//   .create({ record }) → T
//   .update({ id, record }) → { id: string, fields: Partial<T> }
//   .delete({ id }) → { success: true, id: string }
//   .bulkCreate({ records, matchOn? }) → { success: boolean, records: T[] }
//     up to 100 records per call; matchOn upserts on those fields
//
// Reading these types:
//   SDK names are stable identifiers — they do NOT change when a table or field is
//   renamed. Each carries its current user-facing name in quotes (// "Task Name").
//   Where the two differ the field was renamed, and the quoted name is what it means
//   now — treat it as the source of truth.
//   Values are RAW: dates are ISO strings, durations are seconds. Format them for
//   display yourself, following the display config in each field's comment.
//   PERCENT fields are stored as decimals — 0.5 is 50%, 1.0 is 100%.
//   LINKED RECORD fields hold UUID record ids from findOne/findAll — never invent one.
//   Computed and system-managed fields (formula, rollup, lookup, autonumber,
//   created/updated timestamps and more) are absent from the *Input types —
//   a write to one is rejected or silently dropped.
//
// Zite auth users:
//   zite.auth.findAllUsers({ appIds?, filter?, filters?, sort?, limit?, offset? })
//     Supports the same filter, sort, and pagination options as table .findAll()
//     appIds restricts results to users belonging to any listed app
//   zite.auth.updateUserProfile(userId, { firstName?, lastName?, image? })
//   User email addresses cannot be updated through this API
//
// Raw SQL (read-only SELECTs for aggregates, joins, multi-table queries):
//   zite.sql({ query: "SELECT ...", params?: [...] })
//     → { rows: Record<string, unknown>[], columns, rowCount, truncated }
//     Capped at 2000 rows — `truncated: true` means there were more, so paginate in
//     SQL rather than assuming you got everything. Queries time out after 10s.
//     columns[].name is the SDK name; columns[].originalName is the underlying
//     database column (or your own SQL alias).
//
// SQL guidelines:
//   - Use SDK names for tables (PascalCase) and fields (camelCase)
//   - ALWAYS double-quote every identifier: FROM "Orders", WHERE "status" = $1
//   - Use params array for user input ($1, $2, ...): never interpolate into SQL
//   - Auth users are available as "ziteUsers" with id, name, email, firstName, lastName, and image
//   - Soft-deleted rows are excluded automatically — no WHERE deleted_at IS NULL
//   - SELECT only — use .create/.update/.delete for writes
//   - Load the "zite:sql" skill for full SQL reference (formulas, lookups, etc.)
//
// Link tables for zite.sql() JOINs (use these exact names):
//   "PlanExercisesWorkoutPlans" — columns: "planExercisesId", "workoutPlansId" (joins "Plan Exercises" and "Workout Plans")
//   "ExercisesPlanExercises" — columns: "exercisesId", "planExercisesId" (joins "Exercises" and "Plan Exercises")
//   "WorkoutPlansWorkoutSessions" — columns: "workoutPlansId", "workoutSessionsId" (joins "Workout Plans" and "Workout Sessions")
//   "ExerciseLogsWorkoutSessions" — columns: "exerciseLogsId", "workoutSessionsId" (joins "Exercise Logs" and "Workout Sessions")
//   "ExerciseLogsExercises" — columns: "exerciseLogsId", "exercisesId" (joins "Exercise Logs" and "Exercises")
//   "ExercisesFavoriteExercises" — columns: "exercisesId", "favoriteExercisesId" (joins "Exercises" and "Favorite Exercises")
import { createTableClient, createSqlClient, createAuthClient } from 'zitejs/runtime';

/** An attachment as returned when reading a record. */
export type ZiteAttachment = {
  /** Original filename as uploaded. */
  filename: string;
  /** Display name — may differ from `filename`. */
  originalName: string;
  /** File size in bytes. */
  size: number;
  mimeType: string;
  /** Publicly accessible URL. */
  url: string;
  /** ISO timestamp of the upload. */
  uploadedAt: string;
  metadata?: Record<string, unknown>;
};

/** What you may write to an attachments field: a URL, a URL with a name, or an attachment you read earlier. */
export type ZiteAttachmentInput =
  | string
  | { url: string; filename?: string }
  | ZiteAttachment;

/** A record in the "Profiles" table, as it is read back. */
export type ProfilesRecordType = {
  id: string;
  /** Primary field. "Display Name" */
  displayName?: string;
  user?: string | string[];
  /** "Age". 1 decimal places, format: local (e.g. 1,000,000.50) */
  age?: number;
  gender?: "Male" | "Female" | "Other" | string;
  /** "Height". 1 decimal places, format: local (e.g. 1,000,000.50) */
  height?: number;
  /** "Weight". 1 decimal places, format: local (e.g. 1,000,000.50) */
  weight?: number;
  fitnessLevel?: "Beginner" | "Intermediate" | "Advanced" | string;
  fitnessGoal?: "Weight Loss" | "Muscle Gain" | "Strength" | "Endurance" | "Flexibility" | "General Fitness" | string;
  role?: "User" | "Admin" | string;
  avatar?: string;
  /** Read-only. "Created At". Auto-set when record was created (ISO 8601) */
  createdAt?: string;
};

/** What you may write when creating or updating a record in the "Profiles" table. */
export type ProfilesRecordInput = {
  displayName: string | null;
  user: string | string[] | null;
  age: string | number | null;
  gender: "Male" | "Female" | "Other" | string | null;
  height: string | number | null;
  weight: string | number | null;
  fitnessLevel: "Beginner" | "Intermediate" | "Advanced" | string | null;
  fitnessGoal: "Weight Loss" | "Muscle Gain" | "Strength" | "Endurance" | "Flexibility" | "General Fitness" | string | null;
  role: "User" | "Admin" | string | null;
  avatar: string | null;
};

/** A record in the "Exercises" table, as it is read back. */
export type ExercisesRecordType = {
  id: string;
  /** Primary field. "Name" */
  name?: string;
  category?: "Chest" | "Back" | "Shoulders" | "Arms" | "Legs" | "Core" | "Cardio" | "Full Body" | "Yoga" | "Stretching" | string;
  muscleGroup?: "Chest" | "Upper Back" | "Lower Back" | "Shoulders" | "Biceps" | "Triceps" | "Quadriceps" | "Hamstrings" | "Glutes" | "Calves" | "Abs" | "Obliques" | "Full Body" | "Cardio" | string;
  difficulty?: "Beginner" | "Intermediate" | "Advanced" | string;
  equipment?: "No Equipment" | "Dumbbells" | "Resistance Bands" | "Yoga Mat" | "Home Gym" | string;
  instructions?: string;
  steps?: string;
  /** "Default Sets". 1 decimal places, format: local (e.g. 1,000,000.50) */
  defaultSets?: number;
  /** "Default Reps". 1 decimal places, format: local (e.g. 1,000,000.50) */
  defaultReps?: number;
  /** "Default Duration". 0 decimal places, format: local (e.g. 1,000,000.50) */
  defaultDuration?: number;
  /** "Rest Time". 0 decimal places, format: local (e.g. 1,000,000.50) */
  restTime?: number;
  /** "Calories Per Set". 1 decimal places, format: local (e.g. 1,000,000.50) */
  caloriesPerSet?: number;
  /** Links to planExercises ("Plan Exercises"). "Plan Exercises" */
  planExercises?: string | string[];
  /** Links to exerciseLogs ("Exercise Logs"). "Exercise Logs" */
  exerciseLogs?: string | string[];
  /** Links to favoriteExercises ("Favorite Exercises"). "Favorite Exercises" */
  favoriteExercises?: string | string[];
  videoUrl?: string;
  image?: string;
};

/** What you may write when creating or updating a record in the "Exercises" table. */
export type ExercisesRecordInput = {
  name: string | null;
  category: "Chest" | "Back" | "Shoulders" | "Arms" | "Legs" | "Core" | "Cardio" | "Full Body" | "Yoga" | "Stretching" | string | null;
  muscleGroup: "Chest" | "Upper Back" | "Lower Back" | "Shoulders" | "Biceps" | "Triceps" | "Quadriceps" | "Hamstrings" | "Glutes" | "Calves" | "Abs" | "Obliques" | "Full Body" | "Cardio" | string | null;
  difficulty: "Beginner" | "Intermediate" | "Advanced" | string | null;
  equipment: "No Equipment" | "Dumbbells" | "Resistance Bands" | "Yoga Mat" | "Home Gym" | string | null;
  instructions: string | null;
  steps: string | null;
  defaultSets: string | number | null;
  defaultReps: string | number | null;
  defaultDuration: string | number | null;
  restTime: string | number | null;
  caloriesPerSet: string | number | null;
  planExercises: string | string[] | null;
  exerciseLogs: string | string[] | null;
  favoriteExercises: string | string[] | null;
  videoUrl: string | null;
  image: string | null;
};

/** A record in the "Workout Plans" table, as it is read back. */
export type WorkoutPlansRecordType = {
  id: string;
  /** Primary field. "Name" */
  name?: string;
  user?: string | string[];
  goal?: "Weight Loss" | "Muscle Gain" | "Strength" | "Endurance" | "Flexibility" | "General Fitness" | string;
  fitnessLevel?: "Beginner" | "Intermediate" | "Advanced" | string;
  /** "Duration Minutes". 1 decimal places, format: local (e.g. 1,000,000.50) */
  durationMinutes?: number;
  equipment?: "No Equipment" | "Dumbbells" | "Resistance Bands" | "Yoga Mat" | "Home Gym" | string;
  /** "Days Per Week". 1 decimal places, format: local (e.g. 1,000,000.50) */
  daysPerWeek?: number;
  description?: string;
  active?: boolean;
  /** Read-only. "Created At". Auto-set when record was created (ISO 8601) */
  createdAt?: string;
  /** Links to planExercises ("Plan Exercises"). "Plan Exercises" */
  planExercises?: string | string[];
  /** Links to workoutSessions ("Workout Sessions"). "Workout Sessions" */
  workoutSessions?: string | string[];
};

/** What you may write when creating or updating a record in the "Workout Plans" table. */
export type WorkoutPlansRecordInput = {
  name: string | null;
  user: string | string[] | null;
  goal: "Weight Loss" | "Muscle Gain" | "Strength" | "Endurance" | "Flexibility" | "General Fitness" | string | null;
  fitnessLevel: "Beginner" | "Intermediate" | "Advanced" | string | null;
  durationMinutes: string | number | null;
  equipment: "No Equipment" | "Dumbbells" | "Resistance Bands" | "Yoga Mat" | "Home Gym" | string | null;
  daysPerWeek: string | number | null;
  description: string | null;
  active: string | boolean | null;
  planExercises: string | string[] | null;
  workoutSessions: string | string[] | null;
};

/** A record in the "Plan Exercises" table, as it is read back. */
export type PlanExercisesRecordType = {
  id: string;
  /** Primary field. "Label" */
  label?: string;
  /** Links to workoutPlans ("Workout Plans"). "Plan" */
  plan?: string | string[];
  /** Links to exercises ("Exercises"). "Exercise" */
  exercise?: string | string[];
  /** "Day Number". 1 decimal places, format: local (e.g. 1,000,000.50) */
  dayNumber?: number;
  /** "Order". 1 decimal places, format: local (e.g. 1,000,000.50) */
  order?: number;
  /** "Sets". 1 decimal places, format: local (e.g. 1,000,000.50) */
  sets?: number;
  /** "Reps". 1 decimal places, format: local (e.g. 1,000,000.50) */
  reps?: number;
  /** "Duration Seconds". 1 decimal places, format: local (e.g. 1,000,000.50) */
  durationSeconds?: number;
  /** "Rest Seconds". 1 decimal places, format: local (e.g. 1,000,000.50) */
  restSeconds?: number;
};

/** What you may write when creating or updating a record in the "Plan Exercises" table. */
export type PlanExercisesRecordInput = {
  label: string | null;
  plan: string | string[] | null;
  exercise: string | string[] | null;
  dayNumber: string | number | null;
  order: string | number | null;
  sets: string | number | null;
  reps: string | number | null;
  durationSeconds: string | number | null;
  restSeconds: string | number | null;
};

/** A record in the "Workout Sessions" table, as it is read back. */
export type WorkoutSessionsRecordType = {
  id: string;
  /** Primary field. "Title" */
  title?: string;
  user?: string | string[];
  /** Links to workoutPlans ("Workout Plans"). "Plan" */
  plan?: string | string[];
  /** "Date". Date-only field (YYYY-MM-DD string), null when unset, display as "local" format */
  date?: string;
  /** "Duration Minutes". 1 decimal places, format: local (e.g. 1,000,000.50) */
  durationMinutes?: number;
  status?: "In Progress" | "Completed" | "Skipped" | string;
  /** "Calories Burned". 0 decimal places, format: local (e.g. 1,000,000.50) */
  caloriesBurned?: number;
  /** "Total Exercises". 1 decimal places, format: local (e.g. 1,000,000.50) */
  totalExercises?: number;
  /** "Total Sets". 1 decimal places, format: local (e.g. 1,000,000.50) */
  totalSets?: number;
  /** "Total Reps". 1 decimal places, format: local (e.g. 1,000,000.50) */
  totalReps?: number;
  /** "Completion". 0 decimal places */
  completion?: number;
  notes?: string;
  /** Read-only. "Created At". Auto-set when record was created (ISO 8601) */
  createdAt?: string;
  /** Links to exerciseLogs ("Exercise Logs"). "Exercise Logs" */
  exerciseLogs?: string | string[];
};

/** What you may write when creating or updating a record in the "Workout Sessions" table. */
export type WorkoutSessionsRecordInput = {
  title: string | null;
  user: string | string[] | null;
  plan: string | string[] | null;
  date: string | Date | null;
  durationMinutes: string | number | null;
  status: "In Progress" | "Completed" | "Skipped" | string | null;
  caloriesBurned: string | number | null;
  totalExercises: string | number | null;
  totalSets: string | number | null;
  totalReps: string | number | null;
  completion: string | number | null;
  notes: string | null;
  exerciseLogs: string | string[] | null;
};

/** A record in the "Exercise Logs" table, as it is read back. */
export type ExerciseLogsRecordType = {
  id: string;
  /** Primary field. "Label" */
  label?: string;
  /** Links to workoutSessions ("Workout Sessions"). "Session" */
  session?: string | string[];
  /** Links to exercises ("Exercises"). "Exercise" */
  exercise?: string | string[];
  user?: string | string[];
  /** "Set Number". 1 decimal places, format: local (e.g. 1,000,000.50) */
  setNumber?: number;
  /** "Reps". 1 decimal places, format: local (e.g. 1,000,000.50) */
  reps?: number;
  /** "Weight". 1 decimal places, format: local (e.g. 1,000,000.50) */
  weight?: number;
  /** "Duration Seconds". 1 decimal places, format: local (e.g. 1,000,000.50) */
  durationSeconds?: number;
  /** "Rest Seconds". 1 decimal places, format: local (e.g. 1,000,000.50) */
  restSeconds?: number;
  /** "Calories". 1 decimal places, format: local (e.g. 1,000,000.50) */
  calories?: number;
  completed?: boolean;
  /** Read-only. "Created At". Auto-set when record was created (ISO 8601) */
  createdAt?: string;
};

/** What you may write when creating or updating a record in the "Exercise Logs" table. */
export type ExerciseLogsRecordInput = {
  label: string | null;
  session: string | string[] | null;
  exercise: string | string[] | null;
  user: string | string[] | null;
  setNumber: string | number | null;
  reps: string | number | null;
  weight: string | number | null;
  durationSeconds: string | number | null;
  restSeconds: string | number | null;
  calories: string | number | null;
  completed: string | boolean | null;
};

/** A record in the "BMI Records" table, as it is read back. */
export type BmiRecordsRecordType = {
  id: string;
  /** Primary field. "Date". Date-only field (YYYY-MM-DD string), null when unset, display as "local" format */
  date?: string;
  user?: string | string[];
  /** "Weight". 1 decimal places, format: local (e.g. 1,000,000.50) */
  weight?: number;
  /** "Height". 1 decimal places, format: local (e.g. 1,000,000.50) */
  height?: number;
  /** "BMI Value". 1 decimal places, format: local (e.g. 1,000,000.50) */
  bmiValue?: number;
  category?: "Underweight" | "Normal" | "Overweight" | "Obese" | string;
};

/** What you may write when creating or updating a record in the "BMI Records" table. */
export type BmiRecordsRecordInput = {
  date: string | Date | null;
  user: string | string[] | null;
  weight: string | number | null;
  height: string | number | null;
  bmiValue: string | number | null;
  category: "Underweight" | "Normal" | "Overweight" | "Obese" | string | null;
};

/** A record in the "Body Measurements" table, as it is read back. */
export type BodyMeasurementsRecordType = {
  id: string;
  /** Primary field. "Date". Date-only field (YYYY-MM-DD string), null when unset, display as "local" format */
  date?: string;
  user?: string | string[];
  /** "Weight". 1 decimal places, format: local (e.g. 1,000,000.50) */
  weight?: number;
  /** "Chest". 1 decimal places, format: local (e.g. 1,000,000.50) */
  chest?: number;
  /** "Waist". 1 decimal places, format: local (e.g. 1,000,000.50) */
  waist?: number;
  /** "Arms". 1 decimal places, format: local (e.g. 1,000,000.50) */
  arms?: number;
  /** "Hips". 1 decimal places, format: local (e.g. 1,000,000.50) */
  hips?: number;
  /** "Thighs". 1 decimal places, format: local (e.g. 1,000,000.50) */
  thighs?: number;
};

/** What you may write when creating or updating a record in the "Body Measurements" table. */
export type BodyMeasurementsRecordInput = {
  date: string | Date | null;
  user: string | string[] | null;
  weight: string | number | null;
  chest: string | number | null;
  waist: string | number | null;
  arms: string | number | null;
  hips: string | number | null;
  thighs: string | number | null;
};

/** A record in the "Fitness Goals" table, as it is read back. */
export type FitnessGoalsRecordType = {
  id: string;
  /** Primary field. "Name" */
  name?: string;
  user?: string | string[];
  type?: "Weight Target" | "Workout Count" | "Weekly Frequency" | "Strength" | "Custom" | string;
  /** "Target Value". 1 decimal places, format: local (e.g. 1,000,000.50) */
  targetValue?: number;
  /** "Current Value". 1 decimal places, format: local (e.g. 1,000,000.50) */
  currentValue?: number;
  unit?: string;
  /** "Deadline". Date-only field (YYYY-MM-DD string), null when unset, display as "local" format */
  deadline?: string;
  status?: "Active" | "Completed" | "Paused" | "Cancelled" | string;
  /** Read-only. "Created At". Auto-set when record was created (ISO 8601) */
  createdAt?: string;
};

/** What you may write when creating or updating a record in the "Fitness Goals" table. */
export type FitnessGoalsRecordInput = {
  name: string | null;
  user: string | string[] | null;
  type: "Weight Target" | "Workout Count" | "Weekly Frequency" | "Strength" | "Custom" | string | null;
  targetValue: string | number | null;
  currentValue: string | number | null;
  unit: string | null;
  deadline: string | Date | null;
  status: "Active" | "Completed" | "Paused" | "Cancelled" | string | null;
};

/** A record in the "User Achievements" table, as it is read back. */
export type UserAchievementsRecordType = {
  id: string;
  /** Primary field. "Achievement Key" */
  achievementKey?: string;
  user?: string | string[];
  name?: string;
  description?: string;
  icon?: string;
  /** "Unlocked Date". Date-only field (YYYY-MM-DD string), null when unset, display as "local" format */
  unlockedDate?: string;
};

/** What you may write when creating or updating a record in the "User Achievements" table. */
export type UserAchievementsRecordInput = {
  achievementKey: string | null;
  user: string | string[] | null;
  name: string | null;
  description: string | null;
  icon: string | null;
  unlockedDate: string | Date | null;
};

/** A record in the "Reminders" table, as it is read back. */
export type RemindersRecordType = {
  id: string;
  /** Primary field. "Title" */
  title?: string;
  user?: string | string[];
  time?: string;
  days?: ("Monday" | "Tuesday" | "Wednesday" | "Thursday" | "Friday" | "Saturday" | "Sunday" | string)[];
  active?: boolean;
  /** Read-only. "Created At". Auto-set when record was created (ISO 8601) */
  createdAt?: string;
};

/** What you may write when creating or updating a record in the "Reminders" table. */
export type RemindersRecordInput = {
  title: string | null;
  user: string | string[] | null;
  time: string | null;
  days: "Monday" | "Tuesday" | "Wednesday" | "Thursday" | "Friday" | "Saturday" | "Sunday" | string | ("Monday" | "Tuesday" | "Wednesday" | "Thursday" | "Friday" | "Saturday" | "Sunday" | string)[] | null;
  active: string | boolean | null;
};

/** A record in the "Favorite Exercises" table, as it is read back. */
export type FavoriteExercisesRecordType = {
  id: string;
  /** Primary field. "Label" */
  label?: string;
  user?: string | string[];
  /** Links to exercises ("Exercises"). "Exercise" */
  exercise?: string | string[];
};

/** What you may write when creating or updating a record in the "Favorite Exercises" table. */
export type FavoriteExercisesRecordInput = {
  label: string | null;
  user: string | string[] | null;
  exercise: string | string[] | null;
};

export interface ZiteAuthUser {
  id: string;
  name: string;
  email: string;
  firstName?: string;
  lastName?: string;
  image: string | null;
}

export const zite = {
  profiles: createTableClient<ProfilesRecordType, ProfilesRecordInput>('Profiles'), // "Profiles"
  exercises: createTableClient<ExercisesRecordType, ExercisesRecordInput>('Exercises'), // "Exercises"
  workoutPlans: createTableClient<WorkoutPlansRecordType, WorkoutPlansRecordInput>('WorkoutPlans'), // "Workout Plans"
  planExercises: createTableClient<PlanExercisesRecordType, PlanExercisesRecordInput>('PlanExercises'), // "Plan Exercises"
  workoutSessions: createTableClient<WorkoutSessionsRecordType, WorkoutSessionsRecordInput>('WorkoutSessions'), // "Workout Sessions"
  exerciseLogs: createTableClient<ExerciseLogsRecordType, ExerciseLogsRecordInput>('ExerciseLogs'), // "Exercise Logs"
  bmiRecords: createTableClient<BmiRecordsRecordType, BmiRecordsRecordInput>('BmiRecords'), // "BMI Records"
  bodyMeasurements: createTableClient<BodyMeasurementsRecordType, BodyMeasurementsRecordInput>('BodyMeasurements'), // "Body Measurements"
  fitnessGoals: createTableClient<FitnessGoalsRecordType, FitnessGoalsRecordInput>('FitnessGoals'), // "Fitness Goals"
  userAchievements: createTableClient<UserAchievementsRecordType, UserAchievementsRecordInput>('UserAchievements'), // "User Achievements"
  reminders: createTableClient<RemindersRecordType, RemindersRecordInput>('Reminders'), // "Reminders"
  favoriteExercises: createTableClient<FavoriteExercisesRecordType, FavoriteExercisesRecordInput>('FavoriteExercises'), // "Favorite Exercises"
  sql: createSqlClient(),
  auth: createAuthClient<ZiteAuthUser>(),
};
