import {useState} from 'react';
import {Activity} from 'lucide-react';
import {Button} from '@project/components/ui/button';
import {Input} from '@project/components/ui/input';
import {Card} from '@project/components/ui/card';
export default function Auth(){
  const [register,setRegister]=useState(false),[error,setError]=useState(''),[busy,setBusy]=useState(false);
  async function submit(event:React.FormEvent<HTMLFormElement>){event.preventDefault();setBusy(true);setError('');const form=new FormData(event.currentTarget);try{const response=await fetch(`/api/auth/${register?'register':'login'}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(Object.fromEntries(form))});const data=await response.json();if(!response.ok) throw new Error(data.error);const next=new URLSearchParams(location.search).get('next')||'/dashboard';location.assign(next.startsWith('/')&&!next.startsWith('//')&&!next.includes('\\')?next:'/dashboard');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
  return <main className="min-h-screen grid place-items-center p-4 bg-background"><Card className="w-full max-w-md p-8"><a href="/" className="flex gap-2 items-center mb-8 font-bold"><Activity className="text-primary"/>FitTracker</a><h1 className="text-2xl font-bold mb-2">{register?'Create your account':'Welcome back'}</h1><p className="text-muted-foreground mb-6">{register?'Start tracking your home workouts.':'Log in to continue your fitness journey.'}</p><form onSubmit={submit} className="space-y-4">{register&&<label className="block text-sm">Name<Input name="name" required maxLength={100} autoComplete="name" className="mt-1"/></label>}<label className="block text-sm">Email<Input name="email" type="email" required autoComplete="email" className="mt-1"/></label><label className="block text-sm">Password<Input name="password" type="password" required minLength={register?10:1} maxLength={256} autoComplete={register?'new-password':'current-password'} className="mt-1"/>{register&&<span className="text-xs text-muted-foreground">At least 10 characters</span>}</label>{error&&<p role="alert" className="text-primary text-sm">{error}</p>}<Button className="w-full" disabled={busy}>{busy?'Please wait…':register?'Create account':'Log in'}</Button></form><button className="text-sm text-primary mt-6" onClick={()=>{setRegister(!register);setError('')}}>{register?'Already have an account? Log in':'New here? Create an account'}</button></Card></main>;
}
